### PR TITLE
MCE::Util::get_ncpu for android

### PR DESCRIPTION
**Pull request by dkechag**
MCE seems to run OK overall on android (e.g. under terminux), except `MCE::Util::get_ncpu` throws the "unknown os" warning.
Since there is a Linux underlying core with a `/proc/cpuinfo`, the simplest method is to use that.

For reference, on my Snapdragon 8+ gen 1 device it correctly returns ncpu = 8:

```
~ $ cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd46
CPU revision	: 3

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd46
CPU revision	: 3

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd46
CPU revision	: 3

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd46
CPU revision	: 3

processor	: 4
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd47
CPU revision	: 0

processor	: 5
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd47
CPU revision	: 0

processor	: 6
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd47
CPU revision	: 0

processor	: 7
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd48
CPU revision	: 0
```

### CODE REVIEW

**Comment by marioroy** [comment]
Thank you, @dkechag. I will try to make a release in the next few days.

**Comment by marioroy** [comment]
Hi @dkechag. Is there a reason for not counting '^cpu\d' in `/proc/stat`. It's a smaller file. I installed Android in a virtual machine and `/proc/stat` exists. Does the file not exist for you?

**Comment by marioroy** [comment]
I installed Termux on my Android phone. I see the reason. `/proc/stat` requires super privilege. Okay, `/proc/cpuinfo` it is on Android devices. I will add a comment for clarity why `/proc/stat` is not used on Android.

**Comment by dkechag** [comment]
> I installed Termux on my Android phone. I see the reason. `/proc/stat` requires super privilege. Okay, `/proc/cpuinfo` it is on Android devices. I will add a comment for clarity why `/proc/stat` is not used on Android.

That is correct. My first attempt was just adding `|android` to the `linux` entry, but I don't have access to `/proc/stat` on my phone, so the less machine-friendly `/proc/cpuinfo` had to do...

**Comment by marioroy** [comment]
The Android support is competed in MCE and MCE::Shared (GitHub repositories). I tested on an Android phone and x86-Android VM machine.

**Comment by marioroy** [comment]
MCE 1.889 was released and published to Meta::CPAN. This is done.

**Pull request merged**
